version: '3'

services:
  drupal:
    image: drupal
    ports: 
    - '8080:80'
    volumes:
    - /var/www/html/modules
    - /var/www/html/profiles
    - /var/www/html/themes

  postgres:
    image: postgres
    environment: 
    - POSTGRES_PASSWORD=mysecretpassword